---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
non-functional:
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен иметь мобильную версию
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Цена товара в русской версии сайта должна быть в рублях
  - Пользователь должен иметь возможность зарегистрироваться и войти в личный кабинет
  - Описание товаров в русской версии сайта должно быть на русском языке
  - Пользователь должен иметь возможность увеличить фото товара
  - Пользователь должен иметь возможность связаться с тех поддержкой магазина
  - Количество страниц товаров должно быть пронумеровано
  - Пользователь должен иметь возможность выбрать количество товара до его отправки в корзину
  - Корзина должна очищаться после оформления заказа
  - Пользователь должен иметь возможность просматривать и отслеживать заказы
